//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class library
    {
        public int library_id { get; set; }
        public Nullable<int> yazar_id { get; set; }
        public Nullable<int> yayinevi_id { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public Nullable<int> kaynak_id { get; set; }
    
        public virtual kategoriler kategoriler { get; set; }
        public virtual kaynak kaynak { get; set; }
        public virtual yayınevi yayınevi { get; set; }
        public virtual yazarlar yazarlar { get; set; }
    }
}
